### ISSUE TITLE
Question: How do I use modules/diskimage.js ?  Having issues getting it to work.

### ISSUE THREAD

**Issue by Myron-S** [jeffpar/pcjs-diskettes#2]
Ref: https://github.com/jeffpar/pcjs/tree/master/tools

Jeff, hope you can help me on this one. I'm trying to get our diskimages utility to work, but I'm doing something wrong.

I have cloned the pcjs-diskettes using GitHub desktop and am trying to encode to json an a diskette image file.  This is what I'm getting . . .

```
D:\GitHub\pcjs\tools>node modules\diskimage.js f6flpy3289.img f6flpy3289.json
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'glob' imported from D:\Users\mts\GitHub\pcjs\tools\modules\diskimage.js
←[90m    at packageResolve (internal/modules/esm/resolve.js:655:9)←[39m
←[90m    at moduleResolve (internal/modules/esm/resolve.js:696:18)←[39m
←[90m    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)←[39m
←[90m    at Loader.resolve (internal/modules/esm/loader.js:86:40)←[39m
←[90m    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)←[39m
←[90m    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)←[39m
←[90m    at link (internal/modules/esm/module_job.js:55:36)←[39m {
  code: ←[32m'ERR_MODULE_NOT_FOUND'←[39m
}

D:\GitHub\pcjs\tools>
```

In regards to using node.js, I'm a newbie, but not a tech newbie.

I've installed the latest version of node.

```
D:\GitHub\pcjs\tools>node
Welcome to Node.js v14.16.0.
Type ".help" for more information.
>

D:\GitHub\pcjs\tools>
```

What may I be doing wrong?

Can diskimage.js translate a JSON to IMG?

**Comment by jeffpar** [comment]
Did you run `npm install` in your D:\GitHub\pcjs folder after cloning the repo?  That's a one-time pre-requisite.

And yes, it can convert JSON to IMG.  If the first arg is a .json file and the second is a .img file, that's automatic.

**Comment by Myron-S** [comment]
Nope.  Didn't do that.  Now I have.

Is this expected?   (I moved the repo locally on my computer.  Using latest Visual Studio Community IDE)

```
D:\Repos\jeffpar\pcjs>npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: google-closure-compiler-osx@20200112.0.0 (node_modules\google-closure-compiler-osx):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for google-closure-compiler-osx@20200112.0.0: wanted {"os":"darwin","arch":"x64,x86"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: google-closure-compiler-linux@20200112.0.0 (node_modules\google-closure-compiler-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for google-closure-compiler-linux@20200112.0.0: wanted {"os":"linux","arch":"x64,x86"} (current: {"os":"win32","arch":"x64"})

added 606 packages from 503 contributors and audited 678 packages in 53.759s

14 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

D:\Repos\jeffpar\pcjs>
```

**Comment by Myron-S** [comment]
Success.  Thank-you.

```
D:\Repos\jeffpar\pcjs\tools\modules>node diskimage.js
DiskImage v2.04
Copyright © 2012-2021 Jeff Parsons <Jeff@pcjs.org>

nothing to do

D:\Repos\jeffpar\pcjs\tools\modules>
```
